### ISSUE TITLE
Install fails on linux

### ISSUE THREAD

**Issue by meriops** [jonathansmart/BayesGrowth#1]
I can't get your package installed on my archlinux box... Here's what I get when the compilation fails :

```
make: *** [/usr/lib64/R/etc/Makeconf:175: stanExports_Gompertz_stan_model.o] Error 1
ERROR: compilation failed for package ‘BayesGrowth’
```

I reinstalled all stan-related packages etc., but I can't figure out what's wrong. Any hint would be greatly appreciated!

**Comment by jonathansmart** [comment]
Have you tried installing from the tar.gz file or using devtools? Does installation fail using both methods?

**Comment by meriops** [comment]
Yes, both fail. I tried again to install from the tar.gz just now, and I noticed two errors which I hadn't seen before :  

- ERROR: 'configure' exists but is not executable -- see the 'R Installation and Administration Manual'

And then after making the configure file executable and trying again : 

In file included from stanExports_Gompertz_stan_model.cc:5:
In file included from ./stanExports_Gompertz_stan_model.h:20:
In file included from /home/ol/.R/library/rstan/include/rstan/rstaninc.hpp:4:
In file included from /home/ol/.R/library/rstan/include/rstan/stan_fit.hpp:20:
/home/ol/.R/library/rstan/include/rstan/io/rlist_ref_var_context.hpp:200:19: error: no member named 'validate_dims' in namespace 'stan::io'
        stan::io::validate_dims(*this, stage, name, base_type, dims_declared);

Which is probably causing the install fail...

**Comment by jonathansmart** [comment]
Now passes CMD checks
