### ISSUE TITLE
Log parameter error

### ISSUE THREAD

**Issue by duowen9527** [jonathansmart/BayesGrowth#2]
Thank you for providing such an amazing package, but it seems to have some problems. The Log parameter of Estimate_MCMC_Growth appears to have an issue. The LAA values calculated from data_example are too low, resulting in a horizontal line on the graph.
growth_curve_Log
# A tibble: 232 × 7
 Age     LAA   .lower  .upper .width .point .interval
   <dbl>   <dbl>    <dbl>   <dbl>  <dbl> <chr>  <chr>    
 1   0   0.00111 0.000682 0.00144    0.5 mean   qi       
 2   0.1 0.00113 0.000695 0.00147    0.5 mean   qi       
 3   0.2 0.00115 0.000708 0.00150    0.5 mean   qi       
 4   0.3 0.00118 0.000721 0.00153    0.5 mean   qi       
 5   0.4 0.00120 0.000734 0.00155    0.5 mean   qi       
 6   0.5 0.00122 0.000748 0.00158    0.5 mean   qi       
 7   0.6 0.00124 0.000762 0.00161    0.5 mean   qi       
 8   0.7 0.00126 0.000776 0.00164    0.5 mean   qi       
 9   0.8 0.00129 0.000790 0.00167    0.5 mean   qi       
10   0.9 0.00131 0.000805 0.00170    0.5 mean   qi

**Comment by jonathansmart** [comment]
Can you provide some reproduceable code that I can troubleshoot? This is not something that I've encountered from datasets that I have available.
