### ISSUE TITLE
Fails to install, Mac 13.6.1 

### ISSUE THREAD

**Issue by VitalijaBart** [jonathansmart/BayesGrowth#3]
I couldn´t find a way to install it in my R version (R version 4.3.2 (2023-10-31) in mac version 13.6.1.

It also didn´t work with previous R and Mac versions, so I rebooted the whole system, updated everything, but didn´t manage to make it work at the end :(

**Comment by jonathansmart** [comment]
Can you provide the error messages that occur on install? Also have you tried using the tar.gz file that is included on the main page? That might solve the issue. I don't have a Mac so this is difficult for me to troubleshoot.

**Comment by VitalijaBart** [comment]
Unfortunately yes, and it didn´t work. saying its not available for this version of R. 


> install.packages("~/Downloads/BayesGrowth-0.3.5.tar", repos = NULL)
Error in install.packages : type == "both" cannot be used with 'repos = NULL'

In the previous one: 


The downloaded binary packages are in
	/var/folders/59/fb7ghy557q14q_p453j3qcgw0000gn/T//RtmpuPttJn/downloaded_packages
── R CMD build ─────────────────────────────────────────────────────────────────────────────────────────────
✔  checking for file ‘/private/var/folders/59/fb7ghy557q14q_p453j3qcgw0000gn/T/RtmpuPttJn/remotesd8163c21298/jonathansmart-BayesGrowth-c12bd18/DESCRIPTION’ (374ms)
─  preparing ‘BayesGrowth’:
✔  checking DESCRIPTION meta-information ...
─  cleaning src
─  installing the package to build vignettes
E  creating vignettes (4m 30.8s)
   --- re-building ‘MCMC-example.Rmd’ using rmarkdown
   
   Quitting from lines 102-107 [Diagnostics] (MCMC-example.Rmd)
   Error: processing vignette 'MCMC-example.Rmd' failed with diagnostics:
   there is no package called 'bayesplot'
   --- failed re-building ‘MCMC-example.Rmd’
   
   SUMMARY: processing the following file failed:
     ‘MCMC-example.Rmd’
   
   Error: Vignette re-building failed.
   Execution halted
Error: Failed to install 'BayesGrowth' from GitHub:
  ! System command 'R' failed
> browseVignettes("BayesGrowth")
Error in find.package(package, lib.loc) : 
  there is no package called ‘BayesGrowth’
>

**Comment by jonathansmart** [comment]
Thanks! The issue should be fixed now. I added a vignette recently and missed a package from the dependencies. Since you didn't have that package, the vignette wouldn't build and the package installation failed. I've fixed this now so it should work. Can you please try reinstalling the package and let me know how you go? If there is an issue try devtools::install_github("jonathansmart/BayesGrowth") on it's own without the build_vignettes = TRUE argument included.

**Comment by VitalijaBart** [comment]
Thank you so much! Managed to install with without vignettes :)
